services:
  app:
    build: ./
    #restart: on-failure
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dev_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=bG9uZyBzZWNyZXQgdXNlZCBmb3IgS29zdG8=
      - JWT_ISSUER=fudo
    depends_on:
      - db
      - redis
    ports:
      - "9292:9292"

  redis:
    image: redis:alpine3.18
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
