version: "3.7"

services:
  redis:
    image: redis:alpine3.18
    restart: always
    ports:
      - '6379:6379'

  db:
    image:  postgres:16
    restart: always
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '15432:5432'